Adapated xcube cmems using toolbox api
xcube-dev/xcube-cmems pull request #32
Opened 2024-03-22 09:19 UTC by TejasMorbagal

Adapted xcube-cmems implementation due to deprecation of OPeNDAP API and introduction of [Copernicus Marine Toolbox](https://help.marine.copernicus.eu/en/collections/4060068-copernicus-marine-client).

2024-03-25 17:21 UTC, pont-us requested changes
There are a couple of points I'd like to see addressed -- see comment on the example notebook :)

2024-03-25 17:21 UTC, pont-us commented on examples/notebooks/cmems_ds_example.ipynb
This notebook always prompts interactively for my username and password during execution of the "open dataset" cell, even when I've set them in environment variables (and double-checked that the store's picked them up correctly by inspecting the relevant attributes in `store._dataset_opener.cmems`). As far as I can see the code ends up calling through to `subset_cube_with_open_params`, which then calls through to `copernicusmarine` directly rather than using the `Cmems` instance -- could this be the cause?

I also get an interactive prompt in the notebook to confirm overwriting a credentials file whenever I create a new CMEMS store.

I'm a little concerned about these prompts -- I see that in the unit tests they're disabled by patching `click.confirm`. Does that mean that anyone who wants to use the CMEMS store in a headless environment (e.g. as a backend for the xcube viewer) has to patch click to avoid these prompts? If there's really no better way, we should at least document this.

2024-03-26 12:18 UTC, thomasstorm requested changes
Please address my comments (all most of them minor, though)

2024-03-26 12:18 UTC, thomasstorm commented on xcube_cmems/store.py
> +        raise NotImplementedError("search_data() operation is not " "supported yet")
```suggestion
        raise NotImplementedError("search_data() operation is not supported yet")
```

2024-03-26 17:25 UTC, TonioF requested changes
See comment (in addition to what the others said). Also, I noticed that we could use the descibe method from copernicusmarine to implement describe_data without opening the dataset - which makes a lot more sense.

2024-03-27 11:30 UTC, TejasMorbagal commented on test/test_cmems.py
> +    def test_open_data_for_not_exsiting_dataset(self, mock_confirm):
When I started the implementation, I did have a look at describe method of cmems api. But the method returns the whole catalog as a list with metadata about each variable. My impression was open_dataset was more easier and performant than describe. But we could address this as a separate issue. https://github.com/xcube-dev/xcube-cmems/issues/33

2024-03-27 14:11 UTC, TejasMorbagal commented on xcube_cmems/cmems.py
> +                datasets_info.append({"title": product_title, "dataset_id": dataset_id})
Done, dropped comments

2024-03-27 14:19 UTC, TejasMorbagal commented on environment.yml
>    # Required
Done :+1:

2024-03-28 10:59 UTC, TejasMorbagal commented on examples/notebooks/cmems_ds_example.ipynb
The open dataset now doesn't prompt for login credentials if env vars are set. I have changed the prompt behaviour of overwriting credentials files to always True now. This should avoid the prompt atleast. https://help.marine.copernicus.eu/en/articles/8185007-copernicus-marine-toolbox-credentials-configuration

2024-03-28 11:33 UTC, TejasMorbagal commented on pyproject.toml
> +#    "xcube-core",
removed now

2024-03-28 13:11 UTC, thomasstorm approved these changes

2024-04-02 13:21 UTC, TonioF approved these changes

2024-04-02 13:55 UTC, ruchimotwaniBC approved these changes

2024-04-03 09:03 UTC, merged